# Generated by Django 3.2.3 on 2021-05-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
    ]
